### ISSUE TITLE
get_ordered_moves

### ISSUE THREAD

**Issue by HongyiZ** [dengl11/ChineseChessAI#1]
How does get_ordered_moves() in [ABPruning](https://github.com/dengl11/ChineseChessAI/blob/902450e0be2367ab3d0fa162f305848444dca3b2/server/Strategy/ABPruning/ABPruning.ts) achieve sorting by utility value?
get_ordered_moves(agent: Agent) { return agent.get_moves_arr(); }

```
    get_moves_arr() {
        var moves = [];
        for (var movePieceName in this.legalMoves) { //legalMoves: {name: []}
            var toPosList = this.legalMoves[movePieceName];
            for (var i in toPosList) {
                var move = toPosList[i];
                moves.push([movePieceName, move]);
            }
        }
        return moves;
    }```

**Comment by dengl11** [comment]
`get_ordered_moves` is an inherited method of `Agent`, and for `ABPruning` agent, there is no reordering of the moves, so it just uses the unordered moves. Because the point of `ABPruning`  is alpha-beta pruning, not about reordering of moves.

The actually reordering of moves happens in [`MoveReorderPruner`](https://github.com/dengl11/ChineseChessAI/blob/master/server/Strategy/Reorder/Reorder.ts) , which is the child class of `ABPruning`. By comparing `ABPruning` and `MoveReorderPruner`, we can see the effect of reordering of moves, which is improvement of `MoveReorderPruner` upon `ABPruning`.
